Feat: Navigation bar on home page
Ch3ru09/student-website pull request #8
Opened 2023-06-06 20:22 UTC by ZhichGaming

This is my first time using react and contributing to a website so please review.

2023-06-06 20:24 UTC, Ch3ru09 commented on CLIENT/src/app/globals.css
the file has too much css and since we are working with tailwindcss, you souldn't write the css in the index.css file

2023-06-06 20:28 UTC, Ch3ru09 requested changes
change index.css to have less classes and use tailwind classes on the components themselves. Also, change <a> tags with the nextjs <Link> tag [docs](https://nextjs.org/docs/app/api-reference/components/link)

2023-06-07 12:37 UTC, Ch3ru09 approved these changes
It still has some issues with writing conversations but it's fine, I can explain it later

2023-06-07 12:38 UTC, merged

2023-06-07 13:13 UTC, ZhichGaming commented
I don't understand; do you mean something like this?

```
.my-custom-class {
  @apply text-center bg-teal-500 py-2 px-4 rounded-md;
}
```

If so, then what's the difference between regular css? Also, I tried to import an image like this: 

import Logo from "./assets/background.jpg"
<img src={Logo} className="toolbar-logo mr-auto h-8"/>

But unfortunately, it does not work with this error.

```
Type 'StaticImageData' is not assignable to type 'string'.ts(2322)
index.d.ts(2209, 9): The expected type comes from property 'src' which is declared here on type 'DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>'
(property) ImgHTMLAttributes<HTMLImageElement>.src?: string | undefined
```

I also don't understand what you mean by using pathName...

2023-06-07 13:27 UTC, Ch3ru09 commented
so for the first one, tailwind is gonna purge the useless classes for you so performance,

the import logo has to be used with the <Image> tag from nextjs like this
```<Image src={Logo} alt={} />```

use path name is a Hook from nextjs ([docs](https://nextjs.org/docs/app/api-reference/functions/use-pathname))
```const url = usePathname() ```